# edge/nginx.conf
events {
    worker_connections 1024;
}

http {
    # Определение пути кэша и его параметров
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g
                     inactive=60m use_temp_path=off;

    server {
        listen 80;

        location / {
            proxy_pass http://localhost; # Перенаправление запросов на внутренний origin-server
            proxy_cache my_cache; # Активация кэширования
            proxy_cache_valid 200 60m; # Кэшировать успешные ответы (код 200) на 60 минут

            # Добавление заголовка для отслеживания статуса кэша (HIT, MISS, EXPIRED и т.д.)
            add_header X-Proxy-Cache $upstream_cache_status;
        }
    }
}