
server:
  port: ${SERVER_PORT:8084}

spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: reports-frontend
            client-secret: oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/reports-realm
            #user-name-attribute: preferred_username
keycloak:
  server-url: http://localhost:8080
  redirect-uri: http://localhost:8080
  realm: reports-realm
  username: admin1
  password: admin123